name: Build and Push kbs Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    permissions:
      packages: write
    strategy:
      matrix:
        instance:
          - ubuntu-latest
          - s390x
    runs-on: ${{ matrix.instance }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Container Image KBS (built-in AS)
      run: |
        commit_sha=${{ github.sha }}
        arch=$(uname -m)
        DOCKER_BUILDKIT=1 docker build -f kbs/docker/Dockerfile --push \
          -t ghcr.io/confidential-containers/staged-images/kbs:${commit_sha}-${arch} \
          -t ghcr.io/confidential-containers/staged-images/kbs:latest-${arch} \
          --build-arg KBS_FEATURES=coco-as-builtin,openssl,resource,opa --build-arg ARCH=${arch} .

    - name: Build Container Image KBS (gRPC AS)
      run: |
        commit_sha=${{ github.sha }}
        arch=$(uname -m)
        DOCKER_BUILDKIT=1 docker build -f kbs/docker/Dockerfile.coco-as-grpc --push \
          -t ghcr.io/confidential-containers/staged-images/kbs-grpc-as:${commit_sha}-${arch} \
          -t ghcr.io/confidential-containers/staged-images/kbs-grpc-as:latest-${arch} \
          --build-arg ARCH=${arch} .
